### ISSUE TITLE
Build fails on 'is unusable due to shadowed dependencies' -- streaming-commons-0.1.18

### ISSUE THREAD

**Issue by emorris** [tidalcycles/Tidal#229] opened 2017-08-31 02:04 UTC
Having zero getting the build to link all the libs together seems to not like  streaming-commons-0.1.18 at all. 
I reinstalled everything on homebrew but had zero luck. I am assuming something is out of wack with my environment but i really don't know why.. maybe someone has an idea about 
Thanks
```
Waldemar-Daninsky:~ evanmorris$ cabal install tidal -v
/usr/local/bin/alex --version
/usr/bin/gcc -dumpversion
looking for tool haddock near compiler in /usr/local/bin
found haddock in /usr/local/bin/haddock
/usr/local/bin/haddock --version
/usr/local/bin/happy --version
looking for tool hpc near compiler in /usr/local/bin
found hpc in /usr/local/bin/hpc
/usr/local/bin/hpc version
looking for tool hsc2hs near compiler in /usr/local/bin
found hsc2hs in /usr/local/bin/hsc2hs
/usr/local/bin/hsc2hs --version
/usr/local/bin/HsColour -version
/usr/local/bin/ghc -hide-all-packages -c /var/folders/p9/k8052jds3r556386l3zhydcw0000gn/T/59755-0.c -o /var/folders/p9/k8052jds3r556386l3zhydcw0000gn/T/59755-1.o
/usr/bin/ld -x -r /var/folders/p9/k8052jds3r556386l3zhydcw0000gn/T/59755-1.o -o /var/folders/p9/k8052jds3r556386l3zhydcw0000gn/T/59755-2.o
/usr/local/bin/pkg-config --version
looking for tool runghc near compiler in /usr/local/bin
found runghc in /usr/local/bin/runghc
/usr/local/bin/runghc --version
Warning: cannot determine version of /usr/bin/strip :
""
/usr/bin/tar --help
Warning: --root-cmd is no longer supported, see
https://github.com/haskell/cabal/issues/3353 (if you didn't type --root-cmd,
comment out root-cmd in your ~/.cabal/config file)
Reading available packages...
index-state(hackage.haskell.org) = 2017-08-30T22:51:55Z
/usr/local/bin/pkg-config --list-all
/usr/local/bin/pkg-config --modversion libecpg MagickWand-7.Q16HDRI libpng16 libpq apr-util-1 libpgtypes libtiff-4 libpcreposix freetype2 libxslt libcurl nettle libpng libedit p11-kit-1 gdal 'Magick++' hogweed libpcrecpp MagickWand openssl ImageMagick libpcre libxml-2.0 sqlite3 libcrypto libiodbc libssl libecpg_compat yaml-0.1 json-c MagickCore-7.Q16HDRI cloog-isl apr-1 freexl libtasn1 liblzma ImageMagick-7.Q16HDRI gnutls libpcre16 libpcre32 'Magick++-7.Q16HDRI' spatialite libusb-1.0 MagickCore libexslt zlib proj
Resolving dependencies...
Number of threads used: 8.
Extracting
/Users/evanmorris/.cabal/packages/hackage.haskell.org/streaming-commons/0.1.18/streaming-commons-0.1.18.tar.gz
to /var/folders/p9/k8052jds3r556386l3zhydcw0000gn/T/cabal-tmp-59755...
Updating streaming-commons.cabal with the latest revision from the index.
Configuring streaming-commons-0.1.18...
Using self-exec internal setup method with build-type Simple and args:
["act-as-setup","--build-type=Simple","--","configure","--verbose=2","--builddir=dist","--ghc","--prefix=/Users/evanmorris/Library/Haskell","--bindir=/Users/evanmorris/Library/Haskell/bin","--libdir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib","--libsubdir=streaming-commons-0.1.18","--dynlibdir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/x86_64-osx-ghc-8.2.1","--libexecdir=/Users/evanmorris/Library/Haskell/libexec","--libexecsubdir=x86_64-osx-ghc-8.2.1/streaming-commons-0.1.18","--datadir=/Users/evanmorris/Library/Haskell/share","--datasubdir=ghc-8.2.1-x86_64/streaming-commons-0.1.18","--docdir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/streaming-commons-0.1.18/doc","--htmldir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/streaming-commons-0.1.18/doc/html","--haddockdir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/streaming-commons-0.1.18/doc/html","--sysconfdir=/Users/evanmorris/Library/Haskell/etc","--enable-library-profiling","--user","--flags=-use-bytestring-builder","--ipid=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS","--extra-prog-path=/Users/evanmorris/Library/Haskell/bin","--dependency=array=array-0.5.2.0","--dependency=async=async-2.1.1.1-B1zjaWD98Sd3roiQTopWAE","--dependency=base=base-4.10.0.0","--dependency=blaze-builder=blaze-builder-0.4.0.2-8ZspjAKqejL6DPUAcgd0lc","--dependency=bytestring=bytestring-0.10.8.2","--dependency=directory=directory-1.3.0.2","--dependency=network=network-2.6.3.2-8o5F7G3DMrLGgmHkPzZYJx","--dependency=process=process-1.6.1.0","--dependency=random=random-1.1-DtLcP2Z2iOOC0RwcSmXjBK","--dependency=stm=stm-2.4.4.1-2iQ3ZIiQ6vc4AnCVcs8oMd","--dependency=text=text-1.2.2.2-EGUst8sqNAZCw1xLPcmcMH","--dependency=transformers=transformers-0.5.2.0","--dependency=unix=unix-2.7.2.2","--dependency=zlib=zlib-0.6.1.2-LSUQKN12GDNJBVNKQwfLXu","--disable-tests","--exact-configuration","--disable-benchmarks"]
/Library/Haskell/ghc-8.2.1-x86_64/bin/cabal.real act-as-setup
--build-type=Simple -- configure --verbose=2 --builddir=dist --ghc
--prefix=/Users/evanmorris/Library/Haskell
--bindir=/Users/evanmorris/Library/Haskell/bin
--libdir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib
--libsubdir=streaming-commons-0.1.18
--dynlibdir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/x86_64-osx-ghc-8.2.1
--libexecdir=/Users/evanmorris/Library/Haskell/libexec
--libexecsubdir=x86_64-osx-ghc-8.2.1/streaming-commons-0.1.18
--datadir=/Users/evanmorris/Library/Haskell/share
--datasubdir=ghc-8.2.1-x86_64/streaming-commons-0.1.18
--docdir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/streaming-commons-0.1.18/doc
--htmldir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/streaming-commons-0.1.18/doc/html
--haddockdir=/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/streaming-commons-0.1.18/doc/html
--sysconfdir=/Users/evanmorris/Library/Haskell/etc --enable-library-profiling
--user --flags=-use-bytestring-builder
--ipid=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS
--extra-prog-path=/Users/evanmorris/Library/Haskell/bin
--dependency=array=array-0.5.2.0
--dependency=async=async-2.1.1.1-B1zjaWD98Sd3roiQTopWAE
--dependency=base=base-4.10.0.0
--dependency=blaze-builder=blaze-builder-0.4.0.2-8ZspjAKqejL6DPUAcgd0lc
--dependency=bytestring=bytestring-0.10.8.2
--dependency=directory=directory-1.3.0.2
--dependency=network=network-2.6.3.2-8o5F7G3DMrLGgmHkPzZYJx
--dependency=process=process-1.6.1.0
--dependency=random=random-1.1-DtLcP2Z2iOOC0RwcSmXjBK
--dependency=stm=stm-2.4.4.1-2iQ3ZIiQ6vc4AnCVcs8oMd
--dependency=text=text-1.2.2.2-EGUst8sqNAZCw1xLPcmcMH
--dependency=transformers=transformers-0.5.2.0 --dependency=unix=unix-2.7.2.2
--dependency=zlib=zlib-0.6.1.2-LSUQKN12GDNJBVNKQwfLXu --disable-tests
--exact-configuration --disable-benchmarks
Redirecting build log to {handle:
/Users/evanmorris/.cabal/logs/ghc-8.2.1/streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS.log}
Building streaming-commons-0.1.18...
Using self-exec internal setup method with build-type Simple and args:
["act-as-setup","--build-type=Simple","--","build","--verbose=2","--builddir=dist"]
/Library/Haskell/ghc-8.2.1-x86_64/bin/cabal.real act-as-setup
--build-type=Simple -- build --verbose=2 --builddir=dist
Redirecting build log to {handle:
/Users/evanmorris/.cabal/logs/ghc-8.2.1/streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS.log}
Failed to install streaming-commons-0.1.18
Build log ( /Users/evanmorris/.cabal/logs/ghc-8.2.1/streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS.log ):
cabal: Entering directory '/var/folders/p9/k8052jds3r556386l3zhydcw0000gn/T/cabal-tmp-59755/streaming-commons-0.1.18'
Configuring streaming-commons-0.1.18...
Flags chosen: use-bytestring-builder=False
Dependency array ==0.5.2.0: using array-0.5.2.0
Dependency async ==2.1.1.1: using async-2.1.1.1
Dependency base ==4.10.0.0: using base-4.10.0.0
Dependency blaze-builder ==0.4.0.2: using blaze-builder-0.4.0.2
Dependency bytestring ==0.10.8.2: using bytestring-0.10.8.2
Dependency directory ==1.3.0.2: using directory-1.3.0.2
Dependency network ==2.6.3.2: using network-2.6.3.2
Dependency process ==1.6.1.0: using process-1.6.1.0
Dependency random ==1.1: using random-1.1
Dependency stm ==2.4.4.1: using stm-2.4.4.1
Dependency text ==1.2.2.2: using text-1.2.2.2
Dependency transformers ==0.5.2.0: using transformers-0.5.2.0
Dependency unix ==2.7.2.2: using unix-2.7.2.2
Dependency zlib ==0.6.1.2: using zlib-0.6.1.2
Source component graph: component lib
Configured component graph:
    component streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS
        include base-4.10.0.0
        include array-0.5.2.0
        include async-2.1.1.1-B1zjaWD98Sd3roiQTopWAE
        include blaze-builder-0.4.0.2-8ZspjAKqejL6DPUAcgd0lc
        include bytestring-0.10.8.2
        include directory-1.3.0.2
        include network-2.6.3.2-8o5F7G3DMrLGgmHkPzZYJx
        include random-1.1-DtLcP2Z2iOOC0RwcSmXjBK
        include process-1.6.1.0
        include stm-2.4.4.1-2iQ3ZIiQ6vc4AnCVcs8oMd
        include text-1.2.2.2-EGUst8sqNAZCw1xLPcmcMH
        include transformers-0.5.2.0
        include zlib-0.6.1.2-LSUQKN12GDNJBVNKQwfLXu
        include unix-2.7.2.2
        include bytestring-0.10.8.2
Linked component graph:
    unit streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS
        include base-4.10.0.0
        include array-0.5.2.0
        include async-2.1.1.1-B1zjaWD98Sd3roiQTopWAE
        include blaze-builder-0.4.0.2-8ZspjAKqejL6DPUAcgd0lc
        include bytestring-0.10.8.2
        include directory-1.3.0.2
        include network-2.6.3.2-8o5F7G3DMrLGgmHkPzZYJx
        include random-1.1-DtLcP2Z2iOOC0RwcSmXjBK
        include process-1.6.1.0
        include stm-2.4.4.1-2iQ3ZIiQ6vc4AnCVcs8oMd
        include text-1.2.2.2-EGUst8sqNAZCw1xLPcmcMH
        include transformers-0.5.2.0
        include zlib-0.6.1.2-LSUQKN12GDNJBVNKQwfLXu
        include unix-2.7.2.2
        include bytestring-0.10.8.2
        Data.Streaming.Blaze=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Blaze,Data.Streaming.ByteString.Builder=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.ByteString.Builder,Data.Streaming.ByteString.Builder.Buffer=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.ByteString.Builder.Buffer,Data.Streaming.ByteString.Builder.Class=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.ByteString.Builder.Class,Data.Streaming.FileRead=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.FileRead,Data.Streaming.Filesystem=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Filesystem,Data.Streaming.Network=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Network,Data.Streaming.Network.Internal=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Network.Internal,Data.Streaming.Process=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Process,Data.Streaming.Process.Internal=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Process.Internal,Data.Streaming.Text=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Text,Data.Streaming.Zlib=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Zlib,Data.Streaming.Zlib.Lowlevel=streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS:Data.Streaming.Zlib.Lowlevel
Ready component graph:
    definite streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS
        depends base-4.10.0.0
        depends array-0.5.2.0
        depends async-2.1.1.1-B1zjaWD98Sd3roiQTopWAE
        depends blaze-builder-0.4.0.2-8ZspjAKqejL6DPUAcgd0lc
        depends bytestring-0.10.8.2
        depends directory-1.3.0.2
        depends network-2.6.3.2-8o5F7G3DMrLGgmHkPzZYJx
        depends random-1.1-DtLcP2Z2iOOC0RwcSmXjBK
        depends process-1.6.1.0
        depends stm-2.4.4.1-2iQ3ZIiQ6vc4AnCVcs8oMd
        depends text-1.2.2.2-EGUst8sqNAZCw1xLPcmcMH
        depends transformers-0.5.2.0
        depends zlib-0.6.1.2-LSUQKN12GDNJBVNKQwfLXu
        depends unix-2.7.2.2
Using Cabal-2.0.0.2 compiled by ghc-8.2
Using compiler: ghc-8.2.1
Using install prefix: /Users/evanmorris/Library/Haskell
Executables installed in: /Users/evanmorris/Library/Haskell/bin
Libraries installed in:
/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/streaming-commons-0.1.18
Dynamic Libraries installed in:
/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/x86_64-osx-ghc-8.2.1
Private executables installed in:
/Users/evanmorris/Library/Haskell/libexec/x86_64-osx-ghc-8.2.1/streaming-commons-0.1.18
Data files installed in:
/Users/evanmorris/Library/Haskell/share/ghc-8.2.1-x86_64/streaming-commons-0.1.18
Documentation installed in:
/Users/evanmorris/Library/Haskell/ghc-8.2.1-x86_64/lib/streaming-commons-0.1.18/doc
Configuration files installed in: /Users/evanmorris/Library/Haskell/etc
Using alex version 3.2.1 found on system at: /usr/local/bin/alex
Using ar found on system at: /usr/bin/ar
No c2hs found
No cpphs found
No doctest found
Using gcc version 4.2.1 found on system at: /usr/bin/gcc
Using ghc version 8.2.1 found on system at: /usr/local/bin/ghc
Using ghc-pkg version 8.2.1 found on system at: /usr/local/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.18.1 found on system at: /usr/local/bin/haddock
Using happy version 1.19.5 found on system at: /usr/local/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at: /usr/local/bin/hpc
Using hsc2hs version 0.68.2 found on system at: /usr/local/bin/hsc2hs
Using hscolour version 1.24 found on system at: /usr/local/bin/HsColour
No jhc found
Using ld found on system at: /usr/bin/ld
No lhc found
No lhc-pkg found
Using pkg-config version 0.29.2 found on system at: /usr/local/bin/pkg-config
Using runghc version 8.2.1 found on system at: /usr/local/bin/runghc
Using strip found on system at: /usr/bin/strip
Using tar found on system at: /usr/bin/tar
No uhc found
Component build order: library
/usr/local/bin/ghc-pkg init dist/package.conf.inplace
creating dist/build
creating dist/build/autogen
creating dist/build/autogen
Preprocessing library for streaming-commons-0.1.18..
Building library for streaming-commons-0.1.18..
creating dist/build
/usr/local/bin/ghc --make -fbuilding-cabal-package -O -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -i. -idist/build/autogen -idist/build/global-autogen -Idist/build/autogen -Idist/build/global-autogen -Idist/build -Iinclude -optP-include -optPdist/build/autogen/cabal_macros.h -this-unit-id streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS -hide-all-packages -Wmissing-home-modules -package-db dist/package.conf.inplace -package-id base-4.10.0.0 -package-id array-0.5.2.0 -package-id async-2.1.1.1-B1zjaWD98Sd3roiQTopWAE -package-id blaze-builder-0.4.0.2-8ZspjAKqejL6DPUAcgd0lc -package-id directory-1.3.0.2 -package-id network-2.6.3.2-8o5F7G3DMrLGgmHkPzZYJx -package-id random-1.1-DtLcP2Z2iOOC0RwcSmXjBK -package-id process-1.6.1.0 -package-id stm-2.4.4.1-2iQ3ZIiQ6vc4AnCVcs8oMd -package-id text-1.2.2.2-EGUst8sqNAZCw1xLPcmcMH -package-id transformers-0.5.2.0 -package-id zlib-0.6.1.2-LSUQKN12GDNJBVNKQwfLXu -package-id unix-2.7.2.2 -package-id bytestring-0.10.8.2 -XHaskell98 Data.Streaming.Blaze Data.Streaming.ByteString.Builder Data.Streaming.ByteString.Builder.Buffer Data.Streaming.ByteString.Builder.Class Data.Streaming.FileRead Data.Streaming.Filesystem Data.Streaming.Network Data.Streaming.Network.Internal Data.Streaming.Process Data.Streaming.Process.Internal Data.Streaming.Text Data.Streaming.Zlib Data.Streaming.Zlib.Lowlevel Data.Text.Internal.Unsafe.Char Data.Text.Internal.Unsafe.Shift Data.Text.Internal.Encoding.Utf8 Data.Text.Internal.Encoding.Utf16 Data.Text.Internal.Encoding.Utf32
<command line>: cannot satisfy -package-id async-2.1.1.1-B1zjaWD98Sd3roiQTopWAE: 
    async-2.1.1.1-B1zjaWD98Sd3roiQTopWAE is unusable due to shadowed dependencies:
      stm-2.4.4.1-2iQ3ZIiQ6vc4AnCVcs8oMd
    (use -v for more information)
cabal: Leaving directory '/var/folders/p9/k8052jds3r556386l3zhydcw0000gn/T/cabal-tmp-59755/streaming-commons-0.1.18'
World file is already up to date.
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:995:15 in main:Distribution.Client.Install
cabal: Error: some packages failed to install:
streaming-commons-0.1.18-Ij4BOI603DY3tMZTRb3GAS failed during the building
phase. The exception was:
ExitFailure 1
tidal-0.9.4-32124q9Ecl31tISceSlKOD depends on tidal-0.9.4 which failed to
install.
websockets-0.12.2.0-9Bh9qTBrLW83Ec2Xoj414p depends on websockets-0.12.2.0
which failed to install.
Waldemar-Daninsky:~ evanmorris$ 
```

**Comment by vivid-synth** [comment] 2017-09-01 00:13
I think this is an issue with homebrew. I'd recommend removing Haskell completely from your system (https://stackoverflow.com/questions/6884478/everywhere-that-ghc-haskell-platform-installs) and then reinstall (https://www.haskell.org/platform/mac.html)

**Comment by yaxu** [comment] 2017-09-01 08:10
Annoying, seems to be affecting a lot of people at the moment.. Perhaps stack is the way forward.

**Comment by yaxu** [comment] 2017-09-01 09:28
I posted instructions for installing with stack here: http://lurk.org/groups/tidal/messages/topic/3y5O1J1Zdycmb7OJONm1mC/

**Comment by vivid-synth** [comment] 2017-09-01 20:23
This is a very borked setup, I wouldn't blame this on ```cabal-install``` . Homebrew appears to have wreaked havoc; I'm not sure how it got to this state.

**Comment by cannc4** [comment] 2017-09-02 17:14
I can confirm that homebrew is the culprit, not `cabal`. It all worked fine after re-installing Haskell as @vivid-synth suggested.

**Comment by gbaz** [comment] 2017-10-06 06:27
Brew actually just installs the full platform as far as I can tell. The issue was a haskell platform issue, but only with full, and not core. A new binary release of the full platform for mac (https://mail.haskell.org/pipermail/haskell-cafe/2017-October/127979.html) should hopefully resolve this more generally now.

**Comment by yaxu** [comment] 2018-04-22 17:58
This seems to be a homebrew issue, so closing for now.

**Closed** 2018-09-20 21:31 UTC
