### ISSUE TITLE
instance Applicative Pattern does not respect law  pure id <*> v = v

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#257] opened 2017-10-31 16:25 UTC
(this was remarked by a participant of the hackathon)

The Law   https://hackage.haskell.org/package/base-4.10.0.0/docs/Control-Applicative.html says that 
```
pure id <*> v = v
```
but we have, e.g.,
```
*Sound.Tidal.Context> pure id <*> s "x y"
fromList [(s,x)] 0 1

*Sound.Tidal.Context> s "x y"
fromList [(s,x)] 0 1/2
 fromList [(s,y)] 1/2 1
```

**Comment by bgold-cosmos** [comment] 2017-11-02 01:31
This stems from the "structure comes from the left" behavior, and I'm having trouble thinking of a clean way to resolve it (that doesn't break a lot of existing stuff).

**Comment by vivid-synth** [comment] 2017-11-02 01:47
Yeah, this has been an issue for a long time. It's not good that this is broken but I don't really see a way to fix it. Arguably the best thing to do is just to make a different typeclass, not called ```Applicative```, and use that instead (since there is "a definition," it's just not a legal Applicative)

Btw if we do go that route, it would be great to formalize what, in fact, the behavior is!

**Comment by bgold-cosmos** [comment] 2017-11-02 01:56
Is it `Data.Functor.Apply`? (with an additional `pure`-like function that isn't actually pure?)
Apparently that's a "strong lax semi-monoidal endofunctor", and in this context I don't think I understand any of those words.

**Comment by vivid-synth** [comment] 2017-11-02 02:19
Yeah, that is not a very approachable definition haha

I don't think ```Data.Functor.Apply``` helps us, because e.g. ```|*|```, which is defined in terms of ```<$>``` and ```<*>```, is not associative.

Here's an example:

```haskell
d1 $ s "sn*4" (speed "2" |*| n "1 2 3 4")
-- This should, I believe, sound the same - but it doesn't:
d1 $ (s "sn*4" |*| speed "2") |*| n "1 2 3 4"
```

By contrast, these are equal:
```haskell
[(*2),(*3)] <*>  ([(*2),(*3)] <*> [3,4])
(pure (.) <*> [(*2),(*3)] <*>  [(*2),(*3)]) <*> [3,4]
```

This is admittedly not the nicest counter-example, because of the ```pure``` at the beginning. I'm taking the definition from the "Composition" law defined here:

https://wiki.haskell.org/Typeclassopedia#Applicative
```

**Comment by yaxu** [comment] 2017-11-03 00:47
In what other ways could we specify where structure comes from?  I feel like we're missing an elegant solution here..

**Comment by bgold-cosmos** [comment] 2017-11-03 02:19
@vivid-synth : If I understand Apply (not sure I do), I think we'd redefine operators in terms of `<.>` instead of `<*>`, and I think the similar law there:
```
(.) <$> u <.> v <.> w = u <.> (v <.> w)
```
_does_ hold for Patterns.  OTOH, I think semimonoids are supposed to have associativity for the binary operator, so I think Patterns will still fail that.  On the third hand, I don't see how the laws for Data.Functor.Apply actually require associativity.  Only thing I'm sure of is that I don't understand much of this.

@yaxu : I think the immediate "problem" of `pure id <*> v = v` could be solved by saying structure comes from the right, but I'm fairly sure other laws would still have problems - I think the deeper issue is in having the structure "come from" anywhere.  I think for Patterns to be proper Applicative Functors, the structure of `a |*| (b |*| c)`, `(a |*| b) |*| c`, and `(b |*| a) |*| c` should all be the *same*, and even if that's possible I'm not sure it'd be what anyone actually wants.

**Comment by telephon** [comment] 2017-11-03 09:07
>`a |*| (b |*| c)`, `(a |*| b) |*| c`, and `(b |*| a) |*| c` should all be the *same*, 

the case  `(b |*| a) |*| c` wouldn't have to be the same, would it? This would require `|*|` to be commutative.

**Comment by bgold-cosmos** [comment] 2017-11-03 13:16
You're right, I'm confusing commutativity with the interchange law.  

The counterexample to associativity would be how Tidal currently works!  These two are not the same:

```
*Sound.Tidal.Context> n "1 2" |*| (n "4" |*| n "5 6")
fromList [(n,20)] 0 1/2
 fromList [(n,40)] 1/2 1

*Sound.Tidal.Context> (n "1 2" |*| n "4") |*| n "5 6"
fromList [(n,20)] 0 1/2
 fromList [(n,48)] 1/2 1
```

**Comment by telephon** [comment] 2017-11-03 14:38
what causes the `48` instead of the `40` ?

**Comment by telephon** [comment] 2017-11-03 14:40
this is a little confusing indeed. Is it useful?

**Comment by bgold-cosmos** [comment] 2017-11-03 16:05
I don't know about useful, but I'm not 100% sure how to even define a behavior that _guarantees_ associativity.  I think it's easiest if structure comes from both sides in some kind of symmetric way*, but even that gets a bit odd to define for things like `"0 1" + (0.25 ~> "2 3")`.  I think you're forced into a rule like "combination has the largest common substructure", for example `"0 1" + (0.25 ~> "2 3") = "3 2 3 4"`...

* I can't think of a structure rule that's associative but not commutative, but something probably exists

**Comment by yaxu** [comment] 2017-11-03 20:44
Perhaps ordinarily `"0 1" + "1 2 3"` should give neither `"1 3"` or `"1 2 4"` but `"[1 3, 1 2 4]"`
to get existing behaviour you'd stick one pattern 'above' the other like `(layer 1 "0 1") + "1 2 3"`
Then by default `sound` parameters would be on a higher layer than other parameters
and then we could easily make e.g. `<+` where the left hand side is placed 'above' the other and therefore define the structure (as now)

**Comment by telephon** [comment] 2017-11-03 20:54
in APL and SuperCollider similar distinctions are done by adverbs.

```
// in terms of arrays:
[0, 1] + [1, 2, 3]  => [ 1, 3, 3 ]
[0, 1] +.s [1, 2, 3] => [1, 3]
[0, 1] +.x [1, 2, 3] => [ 1, 2, 3, 2, 3, 4 ]

// operator depth:
[0, 1] +.1 [1, 2, 3] => [ [ 1, 2, 3 ], [ 2, 3, 4 ] ]
[0, 1] +.-1 [1, 2, 3] => [ [ 1, 2 ], [ 2, 3 ], [ 3, 4 ] ]

// they are associative:
([0, 1] +.x [1, 2, 3]) +.x [3, 4] == [0, 1] +.x ([1, 2, 3] +.x [3, 4])
```


These specific ones might be useless in tidal, but at least they show a possibility, perhaps.

**Comment by yaxu** [comment] 2017-11-03 23:18
Interesting, reminds me of Haskell's `ZipList` type which just exists to indicate different behaviour when combining lists.

I think the options are limited with Tidal. In my mind it comes down to combining patterns by lining them on top of each other and looking down on them. The upper ones give the structure. If you try to put two patterns on the same level you get a mess.

**Comment by telephon** [comment] 2017-11-04 13:30
>In my mind it comes down to combining patterns by lining them on top of each other and looking down on them.

This makes sense. But this should be associative, shouldn't it?

**Comment by vivid-synth** [comment] 2017-11-20 03:55
> In my mind it comes down to combining patterns by lining them on top of each other and looking down on them. The upper ones give the structure.

This is a really interesting way of looking at it that I hadn't thought of. A ```<+```-ish operator which defines "where the structure is" is intriguing.

**Comment by yaxu** [comment] 2017-11-20 15:08
Ok adding 'layer' sounds like a good way forward then:
```
data Pattern a = Pattern {arc :: Arc -> [Event a], layer :: Layer}
  deriving Typeable
```
I don't know whether layer should be relative or absolute, e.g.:
```
data Layer = Above | Below | Same
```
or
```
type Layer = Int
```
Probably the latter, otherwise I think we'd still have the same problem with associativity.

We could then steal the `>` and `<` operators, a bold move but basically all the arrow-like operators are taken in Haskell and less than / greater than isn't something you use a lot in tidal at the moment.

Then these pairs would be equivalent:
```
d1 $ s "bd sn" < n "0 1 2"
d1 $ s "bd sn" # n "0 1 2"

d1 $ s "bd sn" > n "0 1 2"
d1 $ n "0 1 2" # s "bd sn"

d1 $ s "bd sn" > n "0 1 2" <+ n"<4 8>" 
d1 $ n "0 1 2" # s "bd sn" |+| n "<4 8>"
```
Make sense?

**Comment by jwaldmann** [comment] 2017-11-20 15:18
>  I think you're forced into a rule like "combination has the largest common substructure"

Yes.  Pattern  `p`  describes a periodic infinite sequence. For simplicity, assume `Pattern a=[a]`
(all parts take unit time). Then the semantics of `p :: Pattern a` is `cycle p`, e.g.,

```
take 10 $ cycle "foo"   ==>  "foofoofoof"
```

Then the ZipList Applicative instance is again cyclic, and the period length of `p <*> q` 
is `lcm (length p) (length q)`. 

```
take 10 $ getZipList $ (ZipList $ cycle [id,succ]) <*> (ZipList $ cycle "foo")

==> "fpogopfpog"
```
(period of result is 6). This should nicely fulfil all the laws (where `pure x = cycle [x]`, as it is for ZipList)

Does Tidal have such an operator?

**Comment by yaxu** [comment] 2017-11-20 15:24
But `Pattern a` is not a list of `a`, but a function of `a`, over rational time.

Tidal used to be based on lists, and store a period, with use of `lcm` when combining, but I much prefer the current approach to time which is more flexible in many cases.

**Comment by bgold-cosmos** [comment] 2017-11-20 16:27
There's nothing in the formal specification of Patterns that says anything about periodicity.  `rand` is not periodic (well, technically it has a period of 2^32 or something), and it's trivial to define a pattern such as `Pattern $ \(s,e) -> [((s,e), (s,e), (floor s))]` which never repeats (even in an infinite limit).

For patterns that _are_ periodic it's possible in many cases to deduce the period of combinations using `lcm` or similar.  But I'm not sure that computing the period is even formally decidable if we're given the ability to write arbitrarily complex pattern combinators.

**Comment by yaxu** [comment] 2018-09-08 08:01
Just returning to this, howabout 'structure comes from the smallest elements'?
so `"[1 2] 3" "4 [5 6]"` would give `"[5 6] [8 9]"`?

**Comment by d0kt0r0** [comment] 2018-09-08 12:29
Thinking out loud...
(<+) -- structure from the left
(+>) -- structure from the right
(<+>) -- addition of values with preservation of both structures

**Comment by d0kt0r0** [comment] 2018-09-08 12:37
I realize you need a "default" behaviour for when a pure operation is lifted into Pattern - but that little piece of software trivia need not deflect anything that affects downstream users / use in performance / on the surface. The default behaviour (eg. for liftA2, >>=) could be any of the three cases. But then in practice, in live coding with Tidal, we might define (in addition to the explicit operations like the one in the comment above) our own lifting operators that are similarly explicit about how the structures are combined. liftL liftR liftBoth... no immediate ideas for what good operator equivalents might be.

**Comment by d0kt0r0** [comment] 2018-09-08 15:54
I think pretty much all of the angle bracket + arithmetic operators have a standard meaning in some more or less standard Haskell module... And (notwithstanding what I implied above about not letting backend considerations deflect user/performer experience...) it seems a shame to lose the standard meaning of <*> still. What about running with # for these combinators, since it is already familiar to many TidalCyclers? So:
#-  -- from the left
-# -- from the right
#-# -- from both
#=# -- from both
# -- synonym for #=#

**Comment by d0kt0r0** [comment] 2018-09-08 15:55
(Apparently my last line there triggered some markdown notation! I was saying "#" could be a synonym for #=#)

**Comment by yaxu** [comment] 2018-09-08 16:07
By standard meaning of `<*>` do you mean the haskell standard, or the current tidal standard? The problem is that the current tidal version doesn't conform to the standard applicative laws. This new version is trying to better conform to those laws and so be *more* standard, but to be honest I don't fully understand them..

**Comment by yaxu** [comment] 2018-09-08 16:11
I think I'd like to keep `#` as shorthand for `|=|`, i.e. for replacing values inside patterns of parameters. but then we could have `<=|` (or `<#` as shorthand) for taking structure from the left, and `|=>` (or `#>`) for taking structure from the right as well as values.

**Comment by bgold-cosmos** [comment] 2018-09-08 16:15
In "structure comes from the smallest elements", what about these cases?

`"0 1 2" + "3 4"` = ?  Is it `"3 4 6"` or `"3 [4 5] 6"` or something else?

`"[0, 1 2]" + "[3 4, 5]"` = ?  Since patterns can contain multiple overlapping events I'm not sure if there's always a clear "smallest".

And as I think @yaxu is alluding to in the last comment, I think it may be worthwhile to make a distinction in behavior between operators like `+` on patterns of numerical types, and operators like `#` on ParamPatterns.  For things like `n "c e g a" # s "supersaw"` having a clear "structure from the left" behavior is very nice.  For `"0 1 2" +"3 4"` maybe less so.

**Comment by yaxu** [comment] 2018-09-08 17:15
That'd be `"3 4 6"`
Currently as I envisigate it, it'd first work one way - matching the *onsets* on the right that fit inside the *spans* on the left. It takes the structure from the right, but filters *out* events on the right that are longer than their matched events on the left (in this case, filtering out all of them). Then it does the opposite, and concatenates the two lists.

**Comment by yaxu** [comment] 2018-09-08 17:26
@bgold-cosmos + yes agreed on distinction between `+` and `|+|` etc, although I think with `|/|` and `/` you *don't* want the 'structure to come from the left', because `/` isn't commutative.

**Comment by d0kt0r0** [comment] 2018-09-09 00:00
It seems to me that (1) "different ways of combining structures" and (2) "conforming to Haskell laws for Applicative" are probably issues it is helpful to keep rather separate.

1. In terms of different ways of combining structures, musical utility is probably maximized when you have lots of different combinators and the way they behave is clearly documented. And that's it. In this problem space, then, there is *no* a priori way of deducing a correct behaviour from an arithmetic precedent or a Haskell law. (Concretely: one could certainly have some combinator that divides and takes the structure from the left - because there's no reason not to and it's exactly what might be most expressive in some circumstance. Division is entirely about the value not the structure.)   

2. My understanding of the Applicative laws is shaky to say the least too... However, my instinct is that they are mostly about making sure that (for example) liftA2 (+) "0 1 2" "3 4" gives exactly the same result as liftA2 (+) "3 4" "0 1 2" (ie. result in terms of structure not value, although in the specific case of + it, coincidentally, also gives the same value). Clearly this criterion is *not* met if you go with either the left or the right as the only source of structure, *nor* is it met in *any* variant where some aspect of the structure comes from the left while some other aspect of the structure comes from the right.

I think the "3 [4 5] 6" interpretation is viable for Applicative and also quite musically intuitive. Combining two rhythms by layering them and appreciating the new polyrhythmic rhythm thus created is a super-common feature of many musical cultures!!! I believe we would find quite a few people's musical intuitions are surprised when they collide with the fact of this not being quite the "default" behaviour in many Tidal "idioms".

At first glance the algorithm for this particular case (combining two patterns of discrete events) seems straightforward: Wherever there is an onset in either pattern, there is an onset in the combined pattern, with spans adjusted to the pattern of onsets. Then at each "location" in the resulting structure, each of the input structures are sampled with the sampled values provided to the binary function argument of liftA2 (the + in our example).

Note: It seems to me that this "poly-rhythm" interpretation actually *is* a kind of "smallest structure in a given window" interpretation and that it is rather analogous to the interpretation of lists as non-deterministic computations in "general Haskell", in the way that the number of events in the resulting pattern increases as a non-linear function of the number of events in the input patterns.

(Conversely: simply comparing patterns to decide which one is most detailed (smallest) doesn't sound right (I don't think this is being suggested by anyone - I am just thinking out loud.) Is sine more detailed or less detailed than [1 2 3 4]? I realize in the current Tidal implementation sine leads to one item in the list which might seem like "less detailed" but... that is merely an implementation detail. Conceptually a sine wave that has yet to be sampled seems both more and less detailed than [1 2 3 4] to me.) 

Returning to some of the cases in comments above where "structure coming from the left" was deemed desirable: certainly that should be supported - by "custom" combinators - but I believe it has nothing to do with conforming to the Applicative laws and probably inherently contradicts them. That's no problem though - if you want # to take structure from the left, you can go ahead and define it that way! You just wouldn't be able to define it as a straightforward lifting of a pure function into the Pattern context, while also obeying the laws, but that's no problem, since the laws and what we want to do are quite different things... At the same time, having many combinators that do the polyrhythmic combination thing would be very cool, I'm betting! (with the caveat that this a separate issue from the type of structure combination that happens in Applicative)

Hope that helps! Probably won't be able to respond or think much more about this until Wednesday, btw.

**Comment by yaxu** [comment] 2018-09-09 19:48
Yes that helps thanks, and that does seem a very nice way of doing things. I'll have to try it out!

I agree that a sinewave seems both less detailed (it contains no events) and more detailed (the the higher samplerate, the more values you find).

Having more ways of combining patterns is good. I think there's a choice though between providing more operators for each, or describing how a pattern should be combined as part of its type. Neither seems completely satisfying to me..

**Comment by yaxu** [comment] 2018-09-10 20:07
I think this should do it:
```
  pf <*> px = Pattern f
    where f span = catMaybes $ concat $ map match $ query pf span
            where
              match fe@((fWhole, fPart), f) = map
                                              (\((xWhole, xPart),x) -> do w <- subSpan fWhole xWhole
                                                                          p <- subSpan fPart xPart
                                                                          return ((w,p),f x)
                                              )
                                              (query px fPart)
```

It returns a new pattern, using the timespan you use to query it to get the events from the pattern of functions
For each of these function events, it queries the pattern of values, using the part (the timespan of the event 'fragment')
For each value event, it gets the intersection of it's 'whole' timespan (the span it's a fragment of), and that of the function event, and uses that as the new whole timespan.
It does the same for the parts to get the new part timespan.
(it does this inside the maybe monad, so it copes if the f and x events don't intersect, but they should..)

Does this make sense to anyone? :)

**Comment by bgold-cosmos** [comment] 2018-09-10 22:53
`subSpan`?  Is this in the refactor branch?  I don't see it.

**Comment by yaxu** [comment] 2018-09-10 23:09
Sorry I'll push everything after sleep.. subSpan is a rename of subArc

**Comment by yaxu** [comment] 2018-09-11 08:00
Ok it's there now:
  https://github.com/tidalcycles/Tidal/tree/refactor/src/Sound/Tidal

I moved most of it out into a folder called 'old', am going through moving things back gradually

(I started making tests in `Sound.Tidal.Test`. I tried to make this into a test harness thingie integrated with cabal but gave up with some frustration. anyone familiar with this?)

**Comment by yaxu** [comment] 2018-09-11 10:44
So far the applicative laws are testing out with this.. https://github.com/tidalcycles/Tidal/blob/refactor/src/Sound/Tidal/Test.hs#L82

**Comment by d0kt0r0** [comment] 2018-09-11 19:27
What is the difference between this join and the "built-in" join from Control.Monad?

**Comment by yaxu** [comment] 2018-09-11 20:07
I think it's just that join usually has a standard definition with the meat being the definition of >>=. I'm doing it the other way around but as far as I can tell, that's an ok thing to do.

**Comment by yaxu** [comment] 2018-09-11 21:35
Yes it seems Haskell defines a monad instance via `return` and bind (`>>=`), but that it's also possible to define one via `return`, `join` and `fmap`.  As we already have fmap defined for the functor instance, doing this seems to make some sense..

**Comment by yaxu** [comment] 2018-09-11 21:35
Anyway, closing this for now!

**Closed by yaxu** 2018-09-11 21:35 UTC
