### ISSUE TITLE
Expose websocket or UDP API tidal can be used programatically

### ISSUE THREAD

**Issue by lpil** [tidalcycles/Tidal#167] opened 2017-01-29 16:01 UTC
Currently the main way Tidal is used is through pasting Tidal code into a GHC repl.

If Tidal there was a proper programatic interface like Sonic Pi does we could step towards better editor integration, performance tools, and interesting programmatic experimentation.

**Comment by yaxu** [comment] 2017-01-29 16:46
This does exist as a prototype - see comment on #159, this feels like a duplicate of that issue so will close this one for now

**Closed by yaxu** 2017-01-29 16:46 UTC

**Comment by lpil** [comment] 2017-01-29 16:52
Oh rats, I knew that felt familiar as I was writing it.

**Comment by yaxu** [comment] 2017-01-30 00:15
No worries at all! Let's make some progress on it soon
