### ISSUE TITLE
make arguments of `within` patternable

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#508] opened 2019-04-11 02:09 UTC
Any chance that the `within` function could accept patterns for its arguments?

```
d1 $ within ("0 0.25", "0.5 0.75") $ s "..."
```

I suppose the biggest drawback is that the user could accidentally create a negative arc:

```
within ("0 0.75", "0.5 0.25")
```

What about a new version of within that accepts a pattern for its first argument and a length for its second argument?

```
withinLength ("0 0.75", "0.125")
```

**Comment by bgold-cosmos** [comment] 2019-04-22 16:45
This seems to work:

`withinP (a,b) f p = (tParam2 $ (\g x y q -> within (x,y) g q) f) a b p`

though I don't know if the results are always predictable.  Negative arcs just get ignored since nothing's ever inside them.

**Comment by BenjaminWynn** [comment] 2021-04-13 17:38
I'd love for within to be patternable as well. 

`withinP (a,b) f p = (tParam2 $ (\g x y q -> within (x,y) g q) f) a b p`

This solution does seem to work! Is there a way to make the second number patternable as well @bgold-cosmos? 
I tried messing about but I'm in way over my head. Thanks!

**Comment by ndr-brt** [comment] 2021-11-12 08:30
Some discussions about this happened in #417

**Comment by yaxu** [comment] 2021-11-12 10:15
Yes, a duplicate of #417

**Closed by yaxu** 2021-11-12 10:15 UTC
Labels: Good first issue
